version = 1

[qq-security-center]
display_name = "QQ安全中心"
regions = ["cn-mainland"]
android = ["com.tencent.token"]

[national-anti-fraud-center]
display_name = "国家反诈中心"
regions = ["cn-mainland"]
android = ["com.hicorenational.antifraud"]

[tencent-mobile-manager]
display_name = "腾讯手机管家"
regions = ["cn-mainland"]
android = ["com.tencent.qqpimsecure"]

[360-mobile-security]
display_name = "360手机卫士"
regions = ["cn-mainland"]
android = ["com.qihoo360.mobilesafe"]
